name: meteo

on:
  schedule:
    - cron: '0 19 * * *'  # 每天UTC时间11点，北京时间19点
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install requests

    - name: Run script
      run: |
        python meteo
